{
    "patcher": {
        "fileversion": 1,
        "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
        "classnamespace": "box",
        "rect": [120.0, 120.0, 860.0, 420.0],
        "bglocked": 0,
        "openinpresentation": 0,
        "default_fontsize": 12.0,
        "default_fontface": 0,
        "default_fontname": "Arial",
        "gridonopen": 1,
        "gridsize": [15.0, 15.0],
        "gridsnaponopen": 1,
        "objectsnaponopen": 1,
        "statusbarvisible": 2,
        "toolbarvisible": 1,
        "lefttoolbarpinned": 0,
        "toptoolbarpinned": 0,
        "righttoolbarpinned": 0,
        "bottomtoolbarpinned": 0,
        "toolbars_unpinned_last_save": 0,
        "tallnewobj": 0,
        "boxanimatetime": 200,
        "enablehscroll": 1,
        "enablevscroll": 1,
        "devicewidth": 0.0,
        "description": "Layer C test SFS_MUSICAL_CONTROL source",
        "digest": "",
        "tags": "sfs,test,music-engine,control-source",
        "style": "",
        "subpatcher_template": "",
        "assistshowspatchername": 0,
        "boxes": [
            { "box": { "id": "obj-1", "maxclass": "comment", "text": "Layer C Test Control Source", "patching_rect": [35.0, 25.0, 260.0, 20.0] } },
            { "box": { "id": "obj-2", "maxclass": "comment", "text": "Generates SFS_MUSICAL_CONTROL dictionaries for testing Layer C without Layers A or B.", "patching_rect": [35.0, 55.0, 610.0, 20.0] } },
            { "box": { "id": "obj-3", "maxclass": "message", "text": "calm", "patching_rect": [35.0, 110.0, 60.0, 22.0] } },
            { "box": { "id": "obj-4", "maxclass": "message", "text": "tension", "patching_rect": [105.0, 110.0, 70.0, 22.0] } },
            { "box": { "id": "obj-5", "maxclass": "message", "text": "action", "patching_rect": [185.0, 110.0, 70.0, 22.0] } },
            { "box": { "id": "obj-6", "maxclass": "message", "text": "chaos", "patching_rect": [265.0, 110.0, 70.0, 22.0] } },
            { "box": { "id": "obj-7", "maxclass": "message", "text": "mystery", "patching_rect": [345.0, 110.0, 80.0, 22.0] } },
            { "box": { "id": "obj-8", "maxclass": "message", "text": "scene_change", "patching_rect": [35.0, 155.0, 105.0, 22.0] } },
            { "box": { "id": "obj-9", "maxclass": "message", "text": "accent", "patching_rect": [150.0, 155.0, 70.0, 22.0] } },
            { "box": { "id": "obj-10", "maxclass": "message", "text": "reset_phrase", "patching_rect": [230.0, 155.0, 105.0, 22.0] } },
            { "box": { "id": "obj-11", "maxclass": "message", "text": "events", "patching_rect": [345.0, 155.0, 70.0, 22.0] } },
            { "box": { "id": "obj-12", "maxclass": "newobj", "text": "js sfs.music_engine.control_source.test.js", "patching_rect": [35.0, 225.0, 310.0, 22.0] } },
            { "box": { "id": "obj-13", "maxclass": "outlet", "comment": "SFS_MUSICAL_CONTROL dictionary", "patching_rect": [35.0, 310.0, 30.0, 30.0] } },
            { "box": { "id": "obj-14", "maxclass": "outlet", "comment": "diagnostics", "patching_rect": [160.0, 310.0, 30.0, 30.0] } }
        ],
        "lines": [
            { "patchline": { "source": ["obj-3", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-4", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-5", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-6", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-7", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-8", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-9", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-10", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-11", 0], "destination": ["obj-12", 0] } },
            { "patchline": { "source": ["obj-12", 0], "destination": ["obj-13", 0] } },
            { "patchline": { "source": ["obj-12", 1], "destination": ["obj-14", 0] } }
        ]
    }
}
