{
    "patcher": {
        "fileversion": 1,
        "appversion": {
            "major": 8,
            "minor": 6,
            "revision": 0,
            "architecture": "x64",
            "modernui": 1
        },
        "classnamespace": "box",
        "rect": [100.0, 100.0, 920.0, 430.0],
        "bglocked": 0,
        "openinpresentation": 0,
        "default_fontsize": 12.0,
        "default_fontface": 0,
        "default_fontname": "Arial",
        "gridonopen": 1,
        "gridsize": [15.0, 15.0],
        "gridsnaponopen": 1,
        "objectsnaponopen": 1,
        "statusbarvisible": 2,
        "toolbarvisible": 1,
        "lefttoolbarpinned": 0,
        "toptoolbarpinned": 0,
        "righttoolbarpinned": 0,
        "bottomtoolbarpinned": 0,
        "toolbars_unpinned_last_save": 0,
        "tallnewobj": 0,
        "boxanimatetime": 200,
        "enablehscroll": 1,
        "enablevscroll": 1,
        "devicewidth": 0.0,
        "description": "Layer C Deterministic MIDI Engine for Silent Film Sonific",
        "digest": "",
        "tags": "sfs,music-engine,layer-c,midi",
        "style": "",
        "subpatcher_template": "",
        "assistshowspatchername": 0,
        "boxes": [
            { "box": { "id": "obj-1", "maxclass": "comment", "text": "Layer C: MVP Music Engine", "patching_rect": [35.0, 25.0, 240.0, 20.0] } },
            { "box": { "id": "obj-2", "maxclass": "comment", "text": "Input: SFS_MUSICAL_CONTROL dictionaries, config dictionaries, and transport commands: step, start, stop, reset, panic.", "linecount": 2, "patching_rect": [35.0, 50.0, 760.0, 36.0] } },
            { "box": { "id": "obj-3", "maxclass": "inlet", "comment": "Layer C input / command", "patching_rect": [65.0, 120.0, 30.0, 30.0] } },
            { "box": { "id": "obj-4", "maxclass": "newobj", "text": "js sfs.music_engine.core.deterministic_midi.js", "patching_rect": [65.0, 175.0, 260.0, 22.0] } },
            { "box": { "id": "obj-5", "maxclass": "outlet", "comment": "SFS_CONDUCTOR_CONTEXT dictionary", "patching_rect": [65.0, 285.0, 30.0, 30.0] } },
            { "box": { "id": "obj-6", "maxclass": "outlet", "comment": "SFS_HARMONY_CONTEXT dictionary", "patching_rect": [180.0, 285.0, 30.0, 30.0] } },
            { "box": { "id": "obj-7", "maxclass": "outlet", "comment": "SFS_NOTE_EVENT dictionaries", "patching_rect": [295.0, 285.0, 30.0, 30.0] } },
            { "box": { "id": "obj-8", "maxclass": "outlet", "comment": "SFS_MIDI_EVENT dictionaries", "patching_rect": [410.0, 285.0, 30.0, 30.0] } },
            { "box": { "id": "obj-9", "maxclass": "outlet", "comment": "raw MIDI bytes", "patching_rect": [525.0, 285.0, 30.0, 30.0] } },
            { "box": { "id": "obj-10", "maxclass": "outlet", "comment": "diagnostics / config dictionaries", "patching_rect": [640.0, 285.0, 30.0, 30.0] } },
            { "box": { "id": "obj-11", "maxclass": "comment", "text": "Outlets: conductor, harmony, note events, MIDI lifecycle events, raw MIDI bytes, diagnostics/config.", "patching_rect": [35.0, 350.0, 700.0, 20.0] } }
        ],
        "lines": [
            { "patchline": { "source": ["obj-3", 0], "destination": ["obj-4", 0] } },
            { "patchline": { "source": ["obj-4", 0], "destination": ["obj-5", 0] } },
            { "patchline": { "source": ["obj-4", 1], "destination": ["obj-6", 0] } },
            { "patchline": { "source": ["obj-4", 2], "destination": ["obj-7", 0] } },
            { "patchline": { "source": ["obj-4", 3], "destination": ["obj-8", 0] } },
            { "patchline": { "source": ["obj-4", 4], "destination": ["obj-9", 0] } },
            { "patchline": { "source": ["obj-4", 5], "destination": ["obj-10", 0] } }
        ]
    }
}
