{
    "patcher": {
        "fileversion": 1,
        "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
        "classnamespace": "box",
        "rect": [120.0, 120.0, 800.0, 340.0],
        "bglocked": 0,
        "openinpresentation": 0,
        "default_fontsize": 12.0,
        "default_fontface": 0,
        "default_fontname": "Arial",
        "gridonopen": 1,
        "gridsize": [15.0, 15.0],
        "gridsnaponopen": 1,
        "objectsnaponopen": 1,
        "statusbarvisible": 2,
        "toolbarvisible": 1,
        "lefttoolbarpinned": 0,
        "toptoolbarpinned": 0,
        "righttoolbarpinned": 0,
        "bottomtoolbarpinned": 0,
        "toolbars_unpinned_last_save": 0,
        "tallnewobj": 0,
        "boxanimatetime": 200,
        "enablehscroll": 1,
        "enablevscroll": 1,
        "devicewidth": 0.0,
        "description": "Layer C MIDI lifecycle and raw MIDI output boundary",
        "digest": "",
        "tags": "sfs,music-engine,midi-output",
        "style": "",
        "subpatcher_template": "",
        "assistshowspatchername": 0,
        "boxes": [
            { "box": { "id": "obj-1", "maxclass": "comment", "text": "Layer C MIDI Output", "patching_rect": [35.0, 25.0, 220.0, 20.0] } },
            { "box": { "id": "obj-2", "maxclass": "comment", "text": "Outputs SFS_MIDI_EVENT lifecycle dictionaries and raw MIDI 1.0 bytes. Destination routing is owned by the containing patch.", "linecount": 2, "patching_rect": [35.0, 55.0, 700.0, 36.0] } },
            { "box": { "id": "obj-3", "maxclass": "inlet", "comment": "Layer C input / step / panic", "patching_rect": [65.0, 130.0, 30.0, 30.0] } },
            { "box": { "id": "obj-4", "maxclass": "newobj", "text": "js sfs.music_engine.core.basic.js", "patching_rect": [65.0, 180.0, 260.0, 22.0] } },
            { "box": { "id": "obj-5", "maxclass": "outlet", "comment": "SFS_MIDI_EVENT dictionaries", "patching_rect": [65.0, 245.0, 30.0, 30.0] } },
            { "box": { "id": "obj-6", "maxclass": "outlet", "comment": "raw MIDI bytes", "patching_rect": [180.0, 245.0, 30.0, 30.0] } },
            { "box": { "id": "obj-7", "maxclass": "outlet", "comment": "diagnostics", "patching_rect": [295.0, 245.0, 30.0, 30.0] } }
        ],
        "lines": [
            { "patchline": { "source": ["obj-3", 0], "destination": ["obj-4", 0] } },
            { "patchline": { "source": ["obj-4", 3], "destination": ["obj-5", 0] } },
            { "patchline": { "source": ["obj-4", 4], "destination": ["obj-6", 0] } },
            { "patchline": { "source": ["obj-4", 5], "destination": ["obj-7", 0] } }
        ]
    }
}
